name: Create Release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo run
        env:
          GH_TOKEN: ${{ github.token }}
          CONTAINER_CMD: docker
